# Generated by Django 2.0.6 on 2019-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0003_auto_20190214_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navi',
            name='url',
            field=models.URLField(verbose_name='网址'),
        ),
    ]
